### ISSUE TITLE
Cant Mock HttpHeaderValueCollection in IHttpRequestHeaders

### ISSUE THREAD

**Issue by JoeDM09** [PawelGerr/Thinktecture.Abstractions#2]
When unit of work sets accept headers with a call like `_httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));` the `DefaultRequestHeaders.Accept` is null and cannot be mocked since `HttpHeaderValueCollection<T>` is a sealed class which does not inherit from an interface (excluding enumables like `ICollection`) and does not expose a public constructor.

As soon as I get time I'll try to add some abstractions and put together a PR, but might take a few days.

**Comment by JoeDM09** [comment]
Had a chance to start looking at it this afternoon but can't finish tonight, I'm working it out as I go and trying to follow the same patters you've been using. It's only half done, but if you start looking into this before I finish theres no point double handling things. This is what I've got so far (for better or worst).
https://github.com/JoeDM09/Thinktecture.Abstractions/commit/86c6f5ed4b2ac91516e28533242775b6b9ce50f1

**Comment by JoeDM09** [comment]
Pull Request is live: https://github.com/PawelGerr/Thinktecture.Abstractions/pull/3/files

**Comment by PawelGerr** [comment]
Thank you for the PR, I will review it as soon as I have some free time.
This PR is a breaking change that means I would have to increase the major version to 2.0.0. I'm planing to do that when .NET Standard 2.0 is released but not now. What I can do now is to create a pre-release package `-2.0.0-beta1`.

**Comment by JoeDM09** [comment]
@PawelGerr  If it's a breaking change that would go into a new major version, Then should the same be done for any other similar areas?
I'll try to have a look if I get some time, but if you can think of anywhere else that might need a similar change then it's probably worth doing it all at once.

**Comment by PawelGerr** [comment]
@JoeDM09 I don't think there is a solution without introducing a breaking change.

If there are further enhancements with breaking changes then they should be done all at one. That's why I want to do a pre-release so I have time to collect another PRs.

**Comment by PawelGerr** [comment]
Merged PR and created `2.0.0-beta1`: https://www.nuget.org/packages/Thinktecture.Abstractions/2.0.0-beta1
